name: Go package

on:
  push:
    branches:
      - main  # Adjust this to your default branch if different

jobs:
  build:
    runs-on: ubuntu-latest
    container: docker://docker:20.10.7

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.20'

      - name: Build and Test
        run: |
          go build -v ./...
          go test -v ./...
